name: tunder
repository: https://github.com/tunder-team/tunder

packages:
  - tunder
  - tunder_cli

scripts:
  analyze:
    run: dart analyze . --fatal-infos --fatal-warnings
  format:
    exec: dart format --set-exit-if-changed lib
  test:
    run: |
      dart pub global run coverage:test_with_coverage && $MELOS_ROOT_PATH/tool/combine_coverage.sh
    exec:
      concurrency: 1
  coverage: |
    genhtml coverage/lcov.info -o coverage/html
    open coverage/html/index.html
  pana:
    run: ../tool/pana_score.sh
    exec:
      concurrency: 1

command:
  version:
    linkToCommits: true
    workspaceChangelog: true
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: false
