name: tunder
description: Tunder is a framework designed to build server side applications.
version: 0.1.0
repository: https://github.com/tunder-team/tunder
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  path: ^1.8.1
  http: ^0.13.4
  collection: ^1.16.0
  slugify: ^2.0.0
  recase: ^4.0.0
dev_dependencies:
  dotenv: ^3.0.0
  test: ^1.20.2
