name: tunder
description: Tunder is a framework designed to build server side applications.
version: 0.0.2
repository: https://github.com/tunder-team/tunder
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  path: ^1.8.1
  http: ^0.13.4
  collection: ^1.16.0
  slugify: ^2.0.0
  recase: ^4.0.0
  colorize: ^3.0.0
  inflection3: ^0.5.3+2
  dotenv: ^4.0.1
  postgresql2: ^1.0.3
  args: ^2.3.1
  test: ^1.20.2
dev_dependencies:
  coverage: ^1.3.2
  mocktail: ^0.3.0
